### ISSUE TITLE
ボールアプローチのやり方を改善する

### ISSUE THREAD

**Issue by nabekuro0104** [SSL-Roots/consai_ros2#132]
- 中間位置に収束したかどうかが毎回発生することで遅い気がする
- タイガースがやっているクルッと回って蹴るやつやりたい
- ボール取るときに右肩タックルする
- ボールをなかなか蹴らない
- 衝突回避により、相手 or 味方がボール持っているときに取れない
- 完全にフリーな状態のボールを取りに行くときにも謎の回避動作がはいってしまう
- ボールアプローチがあまりにも遅い

**Comment by uchikun2493** [comment]
#142 で一部対応
- ボールアプローチがあまりにも遅い

実機でないとわからないこと
- ボール取るときに右肩タックルする

未対応
- 中間位置に収束したかどうかが毎回発生することで遅い気がする
- タイガースがやっているクルッと回って蹴るやつやりたい

**Comment by uchikun2493** [comment]
`衝突回避により、相手 or 味方がボール持っているときに取れない`については別の戦略が入るので #142 では未対応

**Comment by uchikun2493** [comment]
#146 でボールの方向を向きながらゲットするように変更した
速度制御と合わせてどうなるのかはまた要検証

**Comment by ShotaAk** [comment]
#207 以降でボールアプローチを改善しているのでクローズします。
