### ISSUE TITLE
ボールプレースメント終了時にボール回避しない

### ISSUE THREAD

**Issue by Yamam0t0** [SSL-Roots/consai_ros2#162]
自チームのボールプレースメントが終了してボールの裏にロボットが向かうときにボールを回避せずにボールに突っ込んでいった

**Comment by ShotaAk** [comment]
この現象は通常のSTOPゲーム中にも観測されました。

**Comment by ShotaAk** [comment]
通常のSTOPゲーム中に回避しない問題と、ボールプレースメント終了時に回避しない問題は別でした。

ボールプレースメント終了時のボール回避問題は、キック動作に起因しています。
