### ISSUE TITLE
シュートされたときに、ゴーリーがレシーブの動きを中断してしまう問題

### ISSUE THREAD

**Issue by nabekuro0104** [SSL-Roots/consai_ros2#64]
- ボールが自ディフェンスエリア外のときはボールの移動予想線に重なるように移動する（ゴール前を守備する）
- ディフェンスエリア内に入った途端に、ボールを取りに行こうとする（ゴール前から離れてボールを迎えに行く）
- 場合によってはボールをするーして得点を許してしまうので危険

（動画の後半、35秒〜がわかりやすい）

https://user-images.githubusercontent.com/38589340/235411347-d452de23-6e9b-4006-af3f-c9bd681ed5b8.mp4

**Comment by ShotaAk** [comment]
放置されているのでクローズします
