### ISSUE TITLE
stopゲーム中のジグザグアプローチ

### ISSUE THREAD

**Issue by nabekuro0104** [SSL-Roots/consai_ros2#66]
- stopゲーム中にボールに近づいてはいけないが、回り込み動作がそれを考慮できていないのでジグザグにアプローチする
- 回り込もうとする、ボールに近づいたので離れる、回り込もうとする…の繰り返しとなって目標地点到達まで時間がかかる

https://user-images.githubusercontent.com/38589340/235413573-79cdb6db-9f99-4114-b166-e0aa56ab3513.mp4

**Comment by uchikun2493** [comment]
メモ：ボール回避のアルゴリズムに問題がある
対象がボールの場合は円周上を移動するなどの回避位置生成が必要
